import Image from 'next/image'

export default function Head() {
    return (
        <div>
            <title>Yours App</title>
            <meta charset="utf-8" />
            <meta content="width=device-width, initial-scale=1.0" name="viewport" />
            <meta name="viewport" content="width=device-width,initial-scale=1" />
            <meta name="description" content="Generated by Next.js" />
            <link rel="icon" href="/favicon.png" />
        </div>
    )
}