"use client";
import Head from "next/head";
import "tailwindcss/tailwind.css";

import "@/styles/global.css";
import Asidebar from "@/components/sidebar/Asidebar";
import Section from "@/components/Section";

import clsx from "clsx";
import Glass from "@/components/login/Glass";
import Nav from "@/components/Nav";

import Footer from "@/components/Footer";
import { Providers } from "./providers";
import { NextUIProvider } from "@nextui-org/system";

import React from "react";

import { ScrollShadow } from "@nextui-org/react";

export default function DashboardRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true} className="dark">
      <Head>
        <title>Yours App</title>
        <meta charSet="utf-8" />
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <meta name="description" content="Generated by Next.js" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <body className="">
        <Providers>
          <Nav />
          <div className="layout">
            <Glass className="w-full mx-auto top-area">
              <div className="sidebar sidebar-dark left-bar left-0 z-30 w-64 transition-transform md:transition-translate-x-full lg:translate-x-0">
                <Asidebar />
              </div>
              <div className="p-0 lg:ml-64">
                <div className="mb-4 pb-36 min-h-screen">
                  <div className="drop-shadow-xl">
                    <main className="layout__main-content">{children}</main>
                  </div>
                </div>
              </div>
            </Glass>
          </div>

          <div className="">
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
