'use client'
import Head from "next/head";
import "tailwindcss/tailwind.css";

import "@/styles/global.css";

import React, { useEffect, useState } from "react";
import useDeviceType from '@/hooks/useDeviceType';
import ConstantContext from "../../context/ConstantContent";


export default function MainRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const device = useDeviceType()
  // const isMobile = device === 'mobile' ? true : false

  const [screenWidth, setScreenWidth] = useState(window.innerWidth);

  useEffect(() => {
    const handleResize = () => {
      setScreenWidth(window.innerWidth);
    };

    window.addEventListener('resize', handleResize);
    handleResize()
    // console.log(screenWidth)
    // Clean up the event listener on component unmount
    return () => {
      window.removeEventListener('resize', handleResize);
    };
  }, [screenWidth]);
  return (
    <html lang="en" suppressHydrationWarning={true} className="dark">
      <Head>
        <title>Yours App</title>
        <meta charSet="utf-8" />
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <meta name="description" content="Generated by Next.js" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <body className="">
        <main className="layout__main-content" >
          <ConstantContext.Provider value={screenWidth}>
            {children}
          </ConstantContext.Provider>
        </main>


      </body>
    </html>
  );
}
