'use client'
import Head from "next/head";
import "tailwindcss/tailwind.css";

import "@/styles/global.css";

import React from "react";
import useDeviceType from '@/hooks/useDeviceType';
import ConstantContext from "../../context/ConstantContent";
export default function MainRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isMobile = useDeviceType() === 'mobile' ? true : false

  return (
    <html lang="en" suppressHydrationWarning={true} className="dark">
      <Head>
        <title>Yours App</title>
        <meta charSet="utf-8" />
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <meta name="description" content="Generated by Next.js" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <body className="">
        <main className="layout__main-content" >
          <ConstantContext.Provider value={isMobile}>
            {/* Other layout elements */}
            {children}
          </ConstantContext.Provider>
        </main>


      </body>
    </html>
  );
}
